FROM java:8

ENV GO_VERSION GO-VERSION-REPLACE-ME

COPY go-server-${GO_VERSION}.deb /tmp/go-server-${GO_VERSION}.deb

RUN dpkg -i /tmp/go-server-${GO_VERSION}.deb

RUN rm -f /tmp/go-server-${GO_VERSION}.deb

CMD /etc/init.d/go-server start && tail -F /var/log/go-server/go-server.log

EXPOSE 8153

EXPOSE 8154
